[project]
name = "crewai_first_impression"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12.9"
dependencies = [
    "crewai[google-genai,tools]>=1.3.0",
    "ddgs>=9.6.1",
]
